---
## Additional tasks not directly related to AlternC

- name: Verify if the pymysql module is installed
  apt:
    name: python-pymysql
    state: present
  tags: alternc:dbuser

- debug:
    var: item
    verbosity: 2
  with_items: "{{ alternc_extra_mysql_users }}"
  tags: alternc:dbuser

- name: create extra mysql users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    login_unix_socket: /run/mysqld/mysqld.sock
    # login_user: root
    # login_password: "{{ root_pass_mysql }}"
    state: "{{ item.state | default ('present') }}"
  with_items: "{{ alternc_extra_mysql_users }}"
  tags: alternc:dbuser
...