---
# tasks file for ansible-AlternC
#########################################################################
## First playbook: https://git.interior.edu.uy/oscarf/alternc35_ansible
### Oscar Ford: oscarf@ei.udelar.edu.uy - Espacio Interdisciplinario, Udelar.
### Convert to role: Cristhian Choque - CCI - UdelaR
### Publish role: Daniel Viñar - CCI - UdelaR (ulvida
###############################################

- name: Verificando sistema operativo y versión.
  assert:
    that:
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version'] | int >= 9
    msg: "Ejecución abortada. El sistema operativo debe ser Debian(9) Stretch."

#- name: Dump all vars
#  action: template src=templates/debug/dumpall.j2 dest=/tmp/ansible.all
- name: ver variables
  debug:
    var: vars


###################################################
#####  Directiva #includedir en /etc/sudoers  #####
###################################################

#X- name: Verificando directiva "#includedir /etc/sudoers.d" en /etc/sudoers
#X  lineinfile:
#X    path: /etc/sudoers
#X    regexp: '^#includedir /etc/sudoers.d$'
#X    line: '#includedir /etc/sudoers.d'
#X    state: present
#X    backup: yes

###############################################################
#####  Agregando repositorio "Koumbit" para AlternC 3.5.  #####
###############################################################

- name: Agregando repositorio "Koumbit" para AlternC 3.5.
  template:
    src: etc/apt/sources.list.d/alternc35.list.j2
    dest: /etc/apt/sources.list.d/alternc35.list


- name: Agregar llave apt de repositorio "Koumbit" para AlternC 3.5.
  apt_key:
    url: "{{ alternc35_repo }}/key.asc"
    state: present


- name: Actualizando lista de paquetes.
  apt:
    update_cache: yes


#################################
#####  acl, quota, mountops #####
#################################

#- name: Instalando paquetes "acl" y "quota".
#  apt:
#    name: "{{ paquetes }}"
#    state: latest
#  vars:
#    paquetes:
#    - acl
#    - quota
#
#- name: Instalando "python-pip" para administrar dependencias del módulo "mountopts". Sea paciente !!.
#  apt:
#    name: python-pip
#    state: latest
#    update_cache: yes
#
#- name: Instalando dependencias para el módulo "mountopts".
#  pip:
#    name: fstab
#    state: latest

#- name: Repaldando fichero "fstab".
#  command: "cp /etc/fstab /etc/fstab.bk.{{ansible_date_time.iso8601_basic}}"
#
#- name: Activando opción "acl" en partición "{{ ansible_pto_montaje_web }}".
#  mountopts:
#    name: "{{ ansible_pto_montaje_web }}"
#    option: acl
#    state: present
#  register: acl_cambio
#
#- name: Activando opción "usrquota" en partición "{{ ansible_pto_montaje_web }}".
#  mountopts:
#    name: "{{ ansible_pto_montaje_web }}"
#    option: usrquota
#    state: present
#  register: usrquota_cambio
#
#- name: Activando opción "grpquota" en partición "{{ ansible_pto_montaje_web }}".
#  mountopts:
#    name: "{{ ansible_pto_montaje_web }}"
#    option: grpquota
#    state: present
#  register: grpquota_cambio
#
#- name: Activando opción "defaults" en partición "{{ ansible_pto_montaje_web }}".
#  mountopts:
#    name: "{{ ansible_pto_montaje_web }}"
#    option: defaults
#    state: present
#  register: defaults_cambio
#
######  Reinicio del sistema. Aplicando nuevas opciones en partición.  #####
#
#- name: Aplicando nuevas opciones en partición "{{ ansible_pto_montaje_web }}". Reinicio del sistema si es necesario.
#  reboot:
#    connect_timeout: 10
#    pre_reboot_delay: 5
#    post_reboot_delay: 10
#  when: (acl_cambio.changed | bool== True) or
#        (usrquota_cambio.changed | bool == True) or
#        (grpquota_cambio.changed | bool == True) or
#        (defaults_cambio.changed | bool == True)
#
######  Iniciando y activando cuotas de disco.  #####
#
#- name: Activando cuotas de disco en "{{ ansible_pto_montaje_web }}".
#  shell: "quotaoff -ugv {{ ansible_pto_montaje_web }}"
#
#- name: Iniciando cuotas de disco en "{{ ansible_pto_montaje_web }}".
#  shell: "quotacheck -cgumv {{ ansible_pto_montaje_web }}"
#
#- name: Activando cuotas de disco en "{{ ansible_pto_montaje_web }}".
#  shell: "quotaon -ugv {{ ansible_pto_montaje_web }}"

##############################
##### Instalación MySql  #####
##############################

- name: Creando credenciales "root" para base de datos MySql.
  template:
    src: root/.my.cnf.j2
    dest: /root/.my.cnf

- name: Instalando servidor de base de datos MySql. Sírvase un café!!. Calme la ansiedad, puede tardar un poco!!.
  apt:
    name: "{{ paquetes }}"
    state: latest
  vars:
    paquetes:
    paquetes:
    - mysql-server
    - mysql-client

#####################
#####  debconf  #####
#####################

- name: Verificando disponibilidad de "debconf" y "debconf-utils" e instalando si es necesario.
  apt:
    name: "{{ paquetes }}"
    state: latest
  vars:
    paquetes:
    - debconf
    - debconf-utils

- name: Fijando opción de configuración (Nombre de dominio completo del panel de hospedaje).
  debconf:
    name: phpmyadmin
    question: phpmyadmin/reconfigure-webserver
    value: "{{ phpmyadmin_debconf_reconfigure_webserver }}"
    vtype: multiselect

- name: Fijando opción de configuración (Nombre de tu servicio de hospedaje).
  debconf:
    name: alternc
    question: alternc/hostingname
    value: "{{ alternc_debconf_hostingname }}"
    vtype: string

- name: Fijando opción de configuración (Nombre de dominio completo del panel de hospedaje).
  debconf:
    name: alternc
    question: alternc/desktopname
    value: "{{ alternc_debconf_desktopname }}"
    vtype: string

- name: Fijando opción de configuración (La ip principal del servidor).
  debconf:
    name: alternc
    question: alternc/public_ip
    value: "{{ alternc_debconf_public_ip }}"
    vtype: string

- name: Fijando opción de configuración (La dirección ip interna del servidor).
  debconf:
    name: alternc
    question: alternc/internal_ip
    value: "{{ alternc_debconf_internal_ip }}"
    vtype: string

- name: Fijando opción de configuración (Nombre de dominio del servidor DNS primario).
  debconf:
    name: alternc
    question: alternc/ns1
    value: "{{ alternc_debconf_ns1 }}"
    vtype: string

- name: Fijando opción de configuración (Nombre de dominio del servidor DNS secundario).
  debconf:
    name: alternc
    question: alternc/ns2
    value: "{{ alternc_debconf_ns2 }}"
    vtype: string

- name: Fijando opción de configuración (El MX por omisión que se asigna a los nuevos dominios).
  debconf:
    name: alternc
    question: alternc/default_mx
    value: "{{ alternc_debconf_default_mx }}"
    vtype: string

- name: Fijando opción de configuración (Se debe utilizar el servidor MySql local identificado automáticamente?).
  debconf:
    name: alternc
    question: alternc/mysql/host
    value: "{{ alternc_debconf_mysql_host }}"
    vtype: string

- name: Fijando opción de configuración (Carpeta en que los archivos HTML de los usuarios AlternC serán almacenados).
  debconf:
    name: alternc
    question: alternc/alternc_html
    value: "{{ alternc_debconf_alternc_html }}"
    vtype: string

- name: Fijando opción de configuración (Carpeta en la que se almacenan los correos de los usuarios).
  debconf:
    name: alternc
    question: alternc/alternc_mail
    value: "{{ alternc_debconf_alternc_mail }}"
    vtype: string

- name: Fijando opción de configuración (Carpeta en la que se almacenarán las bitácoras de AlternC).
  debconf:
    name: alternc
    question: alternc/alternc_logs
    value: "{{ alternc_debconf_alternc_logs }}"
    vtype: string

- name: Fijando opción de configuración (Desea configurar la base de datos para phpmyadmin con dbconfig-common).
  debconf:
    name: phpmyadmin
    question: phpmyadmin/dbconfig-upgrade
    value: "{{ phpmyadmin_debconf_dbconfig_upgrade }}"
    vtype: boolean

- name: Fijando opción de configuración (Contraseña de aplicación MySql para phpmyadmin (1)).
  debconf:
    name: phpmyadmin
    question: phpmyadmin/mysql/admin-pass
    value: "{{ phpmyadmin_debconf_mysql_admin_pass }}"
    vtype: password

- name: Fijando opción de configuración (Contraseña de aplicación MySql para phpmyadmin (2)).
  debconf:
    name: phpmyadmin
    question: phpmyadmin/mysql/app-pass
    value: "{{ phpmyadmin_debconf_mysql_app_pass }}"
    vtype: password

- name: Fijando opción de configuración (Contraseña de aplicación MySql para phpmyadmin (3)).
  debconf:
    name: phpmyadmin
    question: phpmyadmin/app-password-confirm
    value: "{{ phpmyadmin_debconf_app_password_confirm }}"
    vtype: password

- name: Fijando opción de configuración (Desea reinstalar la base de datos phpmyadmin?).
  debconf:
    name: phpmyadmin
    question: phpmyadmin/dbconfig-reinstall
    value: "{{ phpmyadmin_debconf_dbconfig_reinstall }}"
    vtype: boolean

- name: Fijando opción de configuración (Idiomas a soportar (mailman)).
  debconf:
    name: mailman
    question: mailman/site_languages
    value: "{{ mailman_debconf_site_languages }}"
    vtype: multiselect

- name: Fijando opción de configuración (Idioma por omisión para "mailman").
  debconf:
    name: mailman
    question: mailman/default_server_language
    value: "{{ mailman_debconf_default_server_language }}"
    vtype: select

- name: Fijando opción de configuración (Patch mailman proporcionado por "koumbit.org" para el soporte de listas virtuales).
  debconf:
    name: alternc-mailman
    question: alternc-mailman/patch-mailman
    value: "{{ alternc_mailman_debconf_patch_mailman }}"
    vtype: boolean

###########################
#####  debconf (fin)  #####
###########################

###########################################################################################
#####  Instalación de AlternC 3.5, mailman (listas de correo), awstats (estadísticas) #####
###########################################################################################

- name: Instalando AlternC 3.5 (alternc). Tenga paciencia. Espere !!. Mientras puede atender sus redes sociales.
  apt:
    name: "{{ paquetes }}"
    state: latest
  vars:
    paquetes:
    - apt-transport-https
    - alternc

- name: Instalando "mailman", sistema de gestión de listas de correo.
  apt:
    name: alternc-mailman
    state: latest

- name: Iniciando "mailman".
  shell: "/etc/init.d/mailman start"

- name: Instalando "awstats", estadísticas para los sitios web.
  apt:
    name: alternc-awstats
    state: latest

- name: Verificando dominio "{{ alternc_debconf_desktopname }}" en configuración de "awstats".
  lineinfile:
    path: /etc/awstats/awstats.conf
    regexp: 'SiteDomain='
    line: 'SiteDomain="{{ alternc_debconf_desktopname }}"'
    state: present
    backup: yes

- name: Construyendo base de datos para estadísticas (awstats).
  shell: "perl /usr/lib/cgi-bin/awstats.pl -config={{ alternc_debconf_desktopname }} -update"

- name: Configurando política de contraseñas. 10 caracteres mínimo. Mayúsculas, minúsculas y números son obligatorios.
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE policy SET minsize='10', classcount='3''"

- name: Ejecutando alternc.install
  shell: "alternc.install"
  register: resultado_alternc_install

- debug: msg="{{resultado_alternc_install}}"

- name: Recuperando id del administrador (admin).
  shell: mysql {{ alternc_opciones_consulta }} 'SELECT uid FROM membres WHERE login="{{ alternc_admin_user }}"'
  register: user_id

- name: Generando semilla aleatoria de encriptación para el password.
  script: rnd.sh
  register: rnd

- debug: msg="{{user_id}}"

- debug: msg="{{rnd}}"

- name: Estableciendo password de acceso para el administrador AlternC.
  shell: mysql {{ alternc_opciones_consulta }} 'UPDATE membres SET pass=ENCRYPT({{ alternc_admin_pass }}, {{ rnd.stdout }} ) WHERE uid = {{ user_id.stdout }} '

- name: Configurando cuotas por defecto para el administrador.
  shell: mysql {{ alternc_opciones_consulta }} 'UPDATE quotas SET total={{ item.value }} WHERE uid={{ user_id.stdout }} AND name={{ item.key }}'
  loop: "{{ alternc_cuotas_admin }}"

- name: Creando el perfil de cuotas "administrador".
  shell: mysql {{ alternc_opciones_consulta }} 'INSERT INTO defquotas (quota, value, type) VALUES ({{ item.key }}, {{ item.value }}, "administrador")'
  loop: "{{ alternc_cuotas_admin }}"
  ignore_errors: yes

- name: Registrando perfil de cuota "administrador" en la cuenta del administrador.
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE membres SET type=\"administrador\" WHERE uid={{ user_id.stdout }}'"

- name: Definiendo cuota "default" para los usuarios.
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE defquotas SET value={{ item.value }} WHERE quota={{ item.key }} AND type=\"default\"'"
  loop: "{{ alternc_cuotas_usuarios_default }}"

- name: Definiendo otros tipos de cuotas para los usuarios.
  shell: "mysql {{ alternc_opciones_consulta }} 'INSERT INTO defquotas (quota, value, type) VALUES ({{ item.key }}, {{ item.value }}, {{ item.nombre }})'"
  loop: "{{ alternc_cuotas_usuarios }}"
  ignore_errors: yes

- name: Eliminando dominios válidos instalados por defecto.
  shell: "mysql {{ alternc_opciones_consulta }} 'DELETE FROM tld'"

- name: Configurando los nuevos dominios válidos admitidos por AlternC.
  shell: "mysql {{ alternc_opciones_consulta }} 'INSERT INTO tld (tld, mode) VALUES ({{ item }}, '1')'"
  loop: "{{ alternc_dominios_autorizados }}"

- name: Configurando según corresponda el bloqueo de datos en función de la cuota de disco para los usuarios.
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE variable SET value={{ alternc_disk_quota_not_blocking }} WHERE id='17''"

- name: Configurando protocolo de acceso al panel de administración AlternC.
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE variable SET value={{ alternc_force_https }} WHERE id='2''"

- name: Habilitando el registro del debug para AlternC en "/var/log/alternc/bureau.log".
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE variable SET value={{ alternc_debug_panel }} WHERE id='25''"

- name: Configurando email para notificaciones.
  shell: "mysql {{ alternc_opciones_consulta }} 'UPDATE variable SET value={{ alternc_new_email }} WHERE id='26''"

- name: Registrando servidores externos MySql si fueron proporcionados.
  shell: "mysql {{ alternc_opciones_consulta }} 'INSERT INTO db_servers (name, host, login, password, client) VALUES ({{ item.name }}, {{ item.host }}, {{ item.login }}, {{ item.password}}, \"%\")'"
  when:
    - item.name != '""'
    - item.host != '""'
    - item.login != '""'
    - item.password != '""'
  loop: "{{ alternc_db_servers }}"

- name: Generando certificados ssl (certbot-letsencrypt).
  shell: "php /usr/lib/alternc/generate_certbot.php"

- name: Ejecutando alternc.install
  shell: "alternc.install"

- name: Asegurando que los módulos php mas populares se encuentran actualizados e instalados # Módulo de propósito general pero que no se incluye en el instalador de AlternC
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - "php7.0-common"
    - "php7.0-curl"
    - "php7.0-gd"
    - "php7.0-intl"
    - "php7.0-json"
    - "php7.0-mysql"
    - "php7.0-mbstring"
    - "php7.0-mcrypt"
    - "php7.0-imagick"
    - "php7.0-xml"
    - "php7.0-xmlrpc"
    - "php7.0-zip"


- name: Configurando redirección de tráfico HTTP a HTTPS
  template:
    dest: "/etc/apache2/sites-available/000-default.conf"
    src: etc/apache2/sites-available/000-default.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart apache2


#- name: Reiniciando el sistema y finalizando. Buena suerte !!
#  reboot:
#    connect_timeout: 10
#    pre_reboot_delay: 5
#    post_reboot_delay: 10  .
...

