---

- name: Agregando repositorio "Koumbit" para AlternC 3.5.
  template:
    src: etc/apt/sources.list.d/alternc35.list.j2
    dest: /etc/apt/sources.list.d/alternc35.list


- name: Agregar llave apt de repositorio "Koumbit" para AlternC 3.5.
  apt_key:
    url: "{{ alternc35_repo }}/key.asc"
    state: present


- name: Actualizando lista de paquetes.
  apt:
    update_cache: yes


- name: Asegurando que los módulos php mas populares se encuentran actualizados e instalados # Módulos de propósito general pero que no se incluye en el instalador de AlternC
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - "php7.0-common"
    - "php7.0-curl"
    - "php7.0-gd"
    - "php7.0-intl"
    - "php7.0-json"
    - "php7.0-mysql"
    - "php7.0-mbstring"
    - "php7.0-mcrypt"
    - "php7.0-imagick"
    - "php7.0-xml"
    - "php7.0-xmlrpc"
    - "php7.0-zip"