---

- debug: 
    msg: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: include the variable defining the packages for debian version 
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Agregando repositorio para AlternC
  template:
    src: etc/apt/sources.list.d/alternc.list.j2
    dest: /etc/apt/sources.list.d/alternc.list

- name: Agregar llave apt de repositorio AlternC
  apt_key:
    url: "{{ alternc_repo }}/{{ alternc_key }}"
    state: present

- block: 
  - name: definir la estable como distribuci贸n preferida
    lineinfile: 
      path: /etc/apt/apt.conf.d/30StableRelease
      line: 'APT::Default-Release "stable";'
      create: yes
      state: present

  - name: agregar el repositorio de Sid para phpmyadmin, en debian Buster
    apt_repository: 
      repo: "deb {{ url_repo_sid }} {{ url_branch_sid }}"
      state: present
  when: ( ansible_distribution == "Debian") and (ansible_distribution_major_version == "10")

- name: Actualizando lista de paquetes.
  apt:
    update_cache: yes

- name: Asegurando que los m贸dulos php mas populares se encuentran actualizados e instalados # M贸dulos de prop贸sito general pero que no se incluye en el instalador de AlternC
  apt:
    name: "{{ packages }}"
    state: latest
