---

- name: Configurar redirección de tráfico HTTP a HTTPS
  template:
    dest: "/etc/apache2/sites-available/000-default.conf"
    src: etc/apache2/sites-available/000-default.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart apache2


- name: Configurar tamaño máximo permitido en la subida de archivos
  lineinfile:
    path: "/etc/alternc/templates/alternc/apache2.conf"
    regexp: "{{ item.parameter }}"
    insertafter: '<Directory /usr/share/alternc/panel/admin/>'
    line: "  {{ item.parameter }} {{ item.value }}"
    backup: yes
  with_items: "{{ alternc_apache_php_ini_configurations }}"
  tags: phpalternc
  notify:
    - restart apache2


- name: Configurar tamaño máximo permitido en la subida de archivos a PHPMyAdmin
  lineinfile:
    path: "/etc/alternc/templates/alternc/apache2.conf"
    regexp: "{{ item.parameter }}"
    insertafter: '<Directory /usr/share/phpmyadmin>'
    line: "  {{ item.parameter }} {{ item.value }}"
    backup: yes
  with_items: "{{ alternc_phpmyadmin_configurations }}"
  tags: phpalternc
  notify:
    - restart apache2


- name: Asegurar largo suficiente de blowfish_secret
  lineinfile:
    path: "/etc/alternc/templates/alternc/phpmyadmin.inc.php"
    regexp: \$cfg\[\'blowfish_secret\'\]
    line: "$cfg['blowfish_secret'] = '{{ alternc_phpmyadmin_blowfish_secret }}';"
    backup: yes
  tags: phpalternc
  notify:
    - restart apache2


- name: Configurar servidor ProFTPd
  lineinfile:
    path: "/etc/alternc/templates/proftpd/proftpd.conf"
    regexp: "{{ item.parameter }}"
    line: "{{ item.parameter }}        {{ item.value }}"
    backup: yes
  with_items: "{{ alternc_proftpd_configurations }}"
  tags: proftpd
  notify:
    - restart proftpd

- name: Configurar servidor postfix
  lineinfile:
    path: '/etc/postfix/main.cf'
    regexp: "^{{ item.parameter }}"
    line: "{{ item.parameter }} = {{ item.value }}"
    backup: yes
  with_items: "{{ alternc_postfix_main_configurations }}"
  tags: postfix
  notify:
    - restart postfix

- name: Ejecutar alternc.install para reflejar los cambios de configuración
  shell: "alternc.install"
