---
# handlers file for ansible-AlternC

- name: run alternc.install
  shell: "alternc.install"
  register: resultado_alternc_install

- name: run alternc.install 2
  shell: "alternc.install"
  register: resultado_alternc_install2

- name: AlternC - Restart Apache2
  service:
    name: apache2
    state: restarted

- name: AlternC - Restart ProFTPd
  service:
    name: proftpd
    state: restarted

- name: AlternC - Restart Postfix
  service:
    name: postfix
    state: restarted

- name: AlternC - Restart MySQL
  service:
    name: mysql
    state: restarted

...
