---
# handlers file for ansible-AlternC

- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: restart proftpd
  service:
    name: proftpd
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted